using MeetingLive.Core.Services;

namespace MeetingLive.Core.Tests.Services;

public class SuggestedMeetingTitleTests
{
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("\n\n")]
    public void Normalize_WhenMissingOrWhitespace_ReturnsNull(string? raw)
    {
        Assert.Null(SuggestedMeetingTitle.Normalize(raw));
    }

    [Fact]
    public void Normalize_WhenMultipleLines_UsesFirstNonEmptyLine()
    {
        var raw = """

            Q3 planning with Ana
            Extra line the model should not keep
            """;

        var normalized = SuggestedMeetingTitle.Normalize(raw);

        Assert.Equal("Q3 planning with Ana", normalized);
    }

    [Theory]
    [InlineData("# Q3 planning with Ana", "Q3 planning with Ana")]
    [InlineData("## Microphone test", "Microphone test")]
    public void Normalize_WhenLeadingMarkdownHashes_StripsThem(string raw, string expected)
    {
        Assert.Equal(expected, SuggestedMeetingTitle.Normalize(raw));
    }

    [Theory]
    [InlineData("\"Q3 planning with Ana\"", "Q3 planning with Ana")]
    [InlineData("\u201cQ3 planning with Ana\u201d", "Q3 planning with Ana")]
    public void Normalize_WhenWrappedInQuotes_StripsWrappingQuotes(string raw, string expected)
    {
        Assert.Equal(expected, SuggestedMeetingTitle.Normalize(raw));
    }

    [Fact]
    public void Normalize_WhenTrailingPeriod_StripsIt()
    {
        Assert.Equal("Q3 planning with Ana", SuggestedMeetingTitle.Normalize("Q3 planning with Ana."));
    }

    [Fact]
    public void Normalize_WhenLongerThan80Characters_Truncates()
    {
        var raw = new string('a', 90);

        var normalized = SuggestedMeetingTitle.Normalize(raw);

        Assert.NotNull(normalized);
        Assert.Equal(80, normalized.Length);
        Assert.Equal(new string('a', 80), normalized);
    }

    [Theory]
    [InlineData("\"\"")]
    [InlineData("...")]
    [InlineData("###")]
    public void Normalize_WhenEmptyAfterCleaning_ReturnsNull(string raw)
    {
        Assert.Null(SuggestedMeetingTitle.Normalize(raw));
    }

    [Theory]
    [InlineData(null, true)]
    [InlineData("", true)]
    [InlineData("   ", true)]
    [InlineData("Meeting 11 Sep, 15:42", true)]
    [InlineData("meeting 11 Sep, 15:42", true)]
    [InlineData("Meeting 3", true)]
    [InlineData("Meeting with Ana", false)]
    [InlineData("Q3 planning with Ana", false)]
    [InlineData("Meetings 1", false)]
    [InlineData("Standup", false)]
    public void LooksLikePlaceholder_MatchesAutoGeneratedMeetingDateTitles(
        string? currentTitle, bool expected)
    {
        Assert.Equal(expected, SuggestedMeetingTitle.LooksLikePlaceholder(currentTitle));
    }

    [Fact]
    public void FromModelResponse_WhenPlainOneLineTitle_ReturnsNormalizedTitle()
    {
        Assert.Equal("Q3 planning", SuggestedMeetingTitle.FromModelResponse("Q3 planning"));
    }

    [Fact]
    public void FromModelResponse_WhenWrappedInTitleHeading_ReturnsBodyNotHeading()
    {
        var raw = """
            ## Title
            Q3 planning
            """;

        Assert.Equal("Q3 planning", SuggestedMeetingTitle.FromModelResponse(raw));
    }

    [Fact]
    public void FromModelResponse_WhenTitleBlockThenSummary_ReturnsTitleBody()
    {
        var raw = """
            ## Title

            Q3 planning

            ## Summary

            Kickoff.
            """;

        Assert.Equal("Q3 planning", SuggestedMeetingTitle.FromModelResponse(raw));
    }

    [Fact]
    public void FromModelResponse_WhenQuotedPlainTitle_StripsQuotesAndPeriod()
    {
        Assert.Equal("Q3 planning", SuggestedMeetingTitle.FromModelResponse("\"Q3 planning.\""));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void FromModelResponse_WhenEmpty_ReturnsNull(string? raw)
    {
        Assert.Null(SuggestedMeetingTitle.FromModelResponse(raw));
    }

    [Theory]
    [InlineData("## Title")]
    [InlineData("## Title\n\n")]
    [InlineData("## Title\n\n## Summary\n\nNope.")]
    public void FromModelResponse_WhenHeadingOnly_ReturnsNull(string raw)
    {
        Assert.Null(SuggestedMeetingTitle.FromModelResponse(raw));
    }

    [Fact]
    public void Resolve_WhenSuggestedIsNull_ReturnsCurrentTitle()
    {
        const string current = "Meeting 11 Sep, 15:42";

        var resolved = SuggestedMeetingTitle.Resolve(current, suggested: null);

        Assert.Equal(current, resolved);
    }

    [Fact]
    public void Resolve_WhenCurrentIsPlaceholder_ReturnsNormalizedSuggestion()
    {
        var resolved = SuggestedMeetingTitle.Resolve(
            "Meeting 11 Sep, 15:42",
            "  \"Q3 planning with Ana.\"  ");

        Assert.Equal("Q3 planning with Ana", resolved);
    }

    [Fact]
    public void Resolve_WhenCurrentIsEmpty_ReturnsNormalizedSuggestion()
    {
        var resolved = SuggestedMeetingTitle.Resolve(string.Empty, "Microphone test");

        Assert.Equal("Microphone test", resolved);
    }

    [Fact]
    public void Resolve_WhenCurrentIsUserNamed_KeepsCurrentTitle()
    {
        const string current = "Meeting with Ana";

        var resolved = SuggestedMeetingTitle.Resolve(current, "Q3 planning with Ana");

        Assert.Equal(current, resolved);
    }

    [Fact]
    public void Resolve_WhenSuggestedNormalizesToNull_ReturnsCurrentTitle()
    {
        const string current = "Meeting 11 Sep, 15:42";

        var resolved = SuggestedMeetingTitle.Resolve(current, "   ");

        Assert.Equal(current, resolved);
    }
}
